package app

import client.FacebookStreamingClient

object StreamingApp extends App {
  val token = "EAAcAL79ZCFjMBAHiFoLrfmPVpuZAwtNHd2PdGaQ4BSBiZCZBJACy3jiKEimNhava1JyOQbWOSUEbefM533wnyw9vaTDkgSG7tHROqjIFSC2o4fw1d7yqxYam9ZBu0yoZCan7kXRIhcqjZA8X0nLV7cXuaZA95234corjhN2LZAxlmCBk5L3pTEcBFZAHRrn7aSpZAbfJoyzEDFjRAZDZD"
  FacebookStreamingClient().liveComments()
}
